### ISSUE TITLE
Please update the protocol

### ISSUE THREAD

**Issue by lijinhua1993** [agence104/livekit-server-sdk-php#8]
for adaptation livekit version 1.4.2+

```
Google\\Protobuf\\Internal\\GPBDecodeException: Error occurred during parsing: Error occurred during parsing: numPublishers is unknown. in vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:1340
Stack trace:
#0 vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(795): Google\\Protobuf\\Internal\\Message->parseFromJsonStream()
#1 vendor/agence104/livekit-server-sdk/src/WebhookReceiver.php(70): Google\\Protobuf\\Internal\\Message->mergeFromJsonString()
```

**Comment by wzJun1** [comment]
+1

**Comment by p-delorme** [comment]
This will be updated soon.

**Comment by shoaibsharif** [comment]
Is this going to be updated anytime soon? I am having issues receiving webhook:

```
[2023-09-11 20:09:02] local.ERROR: Error occurred during parsing: Error occurred during parsing: numDropped is unknown. {"exception":"[object] (Google\\Protobuf\\Internal\\GPBDecodeException(code: 0): Error occurred during parsing: Error occurred during parsing: numDropped is unknown. at /home/notary/notary-core/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:1340)
[stacktrace]
#0 vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(795): Google\\Protobuf\\Internal\\Message->parseFromJsonStream()
#1 vendor/agence104/livekit-server-sdk/src/WebhookReceiver.php(70): Google\\Protobuf\\Internal\\Message->mergeFromJsonString()
#2 app/Http/Controllers/LiveKitWebhookController.php(21): Agence104\\LiveKit\\WebhookReceiver->receive()
```

**Comment by p-delorme** [comment]
A new version was just released with updated Protocol.
